name: Schedule Workflow

on:
  schedule:
    # The shortest interval GitHub Actions supports is every 5 minutes
    - cron: '*/5 * * * *'
      timezone: Asia/Kolkata
  
jobs:
  trigger_this_workflow_frequently:
    runs-on: ubuntu-latest
    
    steps:
      - name: Task execution
        run: echo "5 minutes (or more) have passed"